name: hr_system_
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.3
  get: ^4.6.6
  jwt_decoder: ^2.0.1
  image_picker: ^1.1.2
  signature: ^6.3.0
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  stream_chat_flutter: ^9.13.0
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  table_calendar: ^3.0.9
  font_awesome_flutter: ^10.8.0
  open_filex: ^4.7.0
  flutter_secure_storage: ^9.2.4
  permission_handler: ^12.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
     - images/
    

 